package kr.ondoc.mapper.sybaseemr.legacy.penchart;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import kr.ondoc.domain.sybase.legacy.penchart.PatientSearchDataVO;
import kr.ondoc.domain.sybase.legacy.penchart.PatientSearchInJaewonDataVO;
import kr.ondoc.domain.sybase.legacy.penchart.PatientSearchInToewonDataVO;
import kr.ondoc.domain.sybase.legacy.penchart.PatientSearchOutCompleteDataVO;
import kr.ondoc.domain.sybase.legacy.penchart.PatientSearchOutDaegiDataVO;
import kr.ondoc.domain.sybase.legacy.penchart.PatientSearchParamVO;

public interface DbOldPatientSearchMapper {
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT rwj_regno,rwj_reg_date,rwj_ptno,rwj_medroom,rwj_name,rwj_yage,rwj_sex,rwj_flag, DATEFORMAT( rwj_time, 'hh:mm:ss' ) as rwj_time, "
			+ "		(SELECT bjg_name FROM jin_gubun WHERE bjg_code=rwj_jin_gubun), "
			+ "		(SELECT bpt_hpno FROM patient WHERE bpt_ptno=rwj_ptno), "
			+ "		(SELECT bji_name FROM jonginfo WHERE bji_code=rwj_jogubun), "
			+ "]]>"
			+ "<if test=\"date2 != null and date2 != ''\">"
			+ "		(SELECT COUNT(*) AS consent_count FROM emrchart AS ec LEFT OUTER JOIN emrsheet_list AS esl ON ec.oec_sid=esl.bes_id "
			+ "		WHERE 0=0 "
			+ "		AND esl.bes_kind in (80,99) AND esl.bes_use='1' AND (ec.oec_state='S' OR ec.oec_state='E')   AND ec.oec_ptno=rwj_ptno AND ec.oec_date=#{date2} ),"
			+ "</if>"
			+ "<![CDATA["
			+ "		bmr_name,bmr_docname,bmr_kwanm,rwj_wait_class,rwj_wait_sclass,rwj_jin_gubun "
			+ "FROM waitjin LEFT OUTER JOIN "
			+ "	(SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "		WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y')) AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "	ON ( bmr_code=rwj_medroom AND bmr_stdate=(SELECT MAX(bmr_stdate) FROM medroom "
			+ "	WHERE bmr_code=rwj_medroom  AND bmr_stdate<=rwj_reg_date "
			+ "		AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y'))) "
			+ "	WHERE 0=0 AND rwj_wait_class!='E' "
			+ "]]>"
			+ "<if test=\"date != null and date != ''\">"
			+ "AND rwj_reg_date=#{date} "
			+ "</if>"
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND bmr_name=#{room_name} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ "AND rwj_name LIKE '%${name}%' "
			+ "</if>"
			+ "ORDER BY rwj_time ASC "
			+ "</script>")
	public List<PatientSearchOutDaegiDataVO> selectPatientSearchOutDaegi(PatientSearchParamVO vo) throws Exception;	
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT rwj_regno,rwj_reg_date,rwj_ptno,rwj_medroom,rwj_name,rwj_yage,rwj_sex,rwj_flag, DATEFORMAT( rwj_time, 'hh:mm:ss' ) as rwj_time, "
			+ "		(SELECT bjg_name FROM jin_gubun WHERE bjg_code=rwj_jin_gubun), "
			+ "		(SELECT bpt_hpno FROM patient WHERE bpt_ptno=rwj_ptno), "
			+ "		(SELECT bji_name FROM jonginfo WHERE bji_code=rwj_jogubun), "
			+ "		bmr_name,bmr_docname,bmr_kwanm,rwj_wait_class,rwj_wait_sclass,rwj_jin_gubun "
			+ "FROM waitjin LEFT OUTER JOIN "
			+ "	(SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "		WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y')) AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "	ON ( bmr_code=rwj_medroom AND bmr_stdate=(SELECT MAX(bmr_stdate) FROM medroom "
			+ "	WHERE bmr_code=rwj_medroom  AND bmr_stdate<=rwj_reg_date "
			+ "		AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y'))) "
			+ "	WHERE 0=0 AND rwj_wait_class!='E' "
			+ "]]>"
			+ "<if test=\"date != null and date != ''\">"
			+ "AND rwj_reg_date=#{date} "
			+ "</if>"
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND bmr_name=#{room_name} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ "AND rwj_name LIKE '%${name}%' "
			+ "</if>"
			+ "ORDER BY rwj_time ASC "
			+ "</script>")
	public List<PatientSearchOutDaegiDataVO> selectPatientSearchOutDaegi2(PatientSearchParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT COUNT(*) AS consent_count FROM emrchart AS ec LEFT OUTER JOIN emrsheet_list AS esl ON ec.oec_sid=esl.bes_id "
			+ "WHERE 0=0 "
			+ "AND esl.bes_kind in (80,99) AND esl.bes_use='1' "
			+ "AND (ec.oec_state='S' OR ec.oec_state='E')   "
			+ "AND ec.oec_ptno=#{ptno} AND ec.oec_date=#{date} "
			+ "]]>"
			+ "</script>")
	public int countConsentCount(String ptno, String date) throws Exception;	
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm, ISNULL(medroom_count, 0) AS medroom_count "
			+ "FROM medroom AS med LEFT OUTER JOIN (SELECT rwj_medroom, count(rwj_medroom) AS medroom_count "
			+ "										FROM waitjin "
			+ "LEFT OUTER JOIN "
			+ "(SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "	WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y')) "
			+ "AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "ON ( bmr_code=rwj_medroom AND bmr_stdate=(SELECT MAX(bmr_stdate) "
			+ "												FROM medroom WHERE bmr_code=rwj_medroom  AND bmr_stdate<=rwj_reg_date "
			+ "]]>"
			+ "												AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y'))) "
			+ "																	WHERE 0=0 AND rwj_wait_class!='E' "
			+ "<if test=\"date != null and date != ''\">"
			+ "												 					AND rwj_reg_date=#{date}"
			+ "</if>"
			+ "  																GROUP BY rwj_medroom) AS temp  "
			+ "ON temp.rwj_medroom=med.bmr_code  WHERE bmr_use='Y' AND bmr_hosnum=(SELECT bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y') "
			+ "</script>")
	public List<PatientSearchOutDaegiDataVO> selectPatientSearchOutDaegiTreate(PatientSearchParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT rwj_medroom, count(rwj_medroom) AS medroom_count FROM waitjin "
			+ "LEFT OUTER JOIN (SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "						WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y')) "
			+ "						AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "ON ( bmr_code=rwj_medroom AND bmr_stdate=(SELECT MAX(bmr_stdate) FROM medroom "
			+ "WHERE bmr_code=rwj_medroom  AND bmr_stdate<=rwj_reg_date AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y'))) "
			+ "WHERE 0=0 AND rwj_wait_class!='E'  "
			+ "]]>"
			+ "<if test=\"date != null and date != ''\">"
			+ "AND rwj_reg_date=#{date} "
			+ "</if>"
			+ "GROUP BY rwj_medroom "
			+ "</script>")
	public List<PatientSearchOutDaegiDataVO> selectPatientSearchOutDaegiCount(PatientSearchParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT onw_regno,onw_ptno,onw_name,onw_sex,onw_yage,onw_ch_date,onw_time, bmr_name,bmr_docname,bmr_kwanm, "
			+ "	(SELECT bjg_name FROM jin_gubun WHERE bjg_code=onw_jin_gubun), "
			+ "]]>"
			+ "<if test=\"date2 != null and date2 != ''\">"
			+ "		(SELECT COUNT(*) AS consent_count FROM emrchart AS ec LEFT OUTER JOIN emrsheet_list AS esl ON ec.oec_sid=esl.bes_id "
			+ "		WHERE 0=0 "
			+ "		AND esl.bes_kind in (80,99) AND esl.bes_use='1' AND (ec.oec_state='S' OR ec.oec_state='E') AND ec.oec_ptno=onw_ptno AND ec.oec_date=#{date2} ),"
			+ "</if>"
			+ "<![CDATA["
			+ "	(SELECT bji_name FROM jonginfo WHERE bji_code=onw_jogubun) "
			+ "FROM naewon "
			+ "LEFT OUTER JOIN (SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "					WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "ON( onw_medroom=bmr_code AND bmr_stdate=(SELECT MAX(bmr_stdate) "
			+ "											FROM medroom "
			+ "											WHERE bmr_code=onw_medroom AND bmr_stdate<=onw_ch_date) "
			+ "												AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "WHERE 0=0 AND NOT(onw_kind LIKE '9%')  "
			+ "AND onw_class LIKE '1%' AND (onw_kind LIKE '1%' OR onw_kind LIKE '3%' OR onw_kind LIKE '5%' OR onw_kind LIKE '_3')  "
			+ "]]>"
			+ "<if test=\"date != null and date != ''\">"
			+ "AND onw_ch_date=#{date} "
			+ "</if>"
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND bmr_name=#{room_name} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ "AND onw_name LIKE '%${name}%' "
			+ "</if>"			
			+ "<if test=\"sort != null and sort != '' and sort == 'name-asc'\">"
			+ "ORDER BY onw_name ASC "
			+ "</if>"
			+ "<if test=\"sort != null and sort != '' and sort == 'name-desc'\">"
			+ "ORDER BY onw_name DESC "
			+ "</if>"
			+ "<if test=\"sort != null and sort != '' and sort == 'time-asc'\">"
			+ "ORDER BY onw_time ASC "
			+ "</if>"
			+ "<if test=\"sort != null and sort != '' and sort == 'time-desc'\">"
			+ "ORDER BY onw_time DESC "
			+ "</if>"
			+ "<if test=\"sort == null or sort == ''\">"
			+ "ORDER BY onw_time ASC "
			+ "</if>"
			+ "</script>")
	public List<PatientSearchOutCompleteDataVO> selectPatientSearchOutComplete(PatientSearchParamVO vo) throws Exception;	
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT onw_regno,onw_ptno,onw_name,onw_sex,onw_yage,onw_ch_date,onw_time, bmr_name,bmr_docname,bmr_kwanm, "
			+ "	(SELECT bjg_name FROM jin_gubun WHERE bjg_code=onw_jin_gubun), "
			+ "	(SELECT bji_name FROM jonginfo WHERE bji_code=onw_jogubun) "
			+ "FROM naewon "
			+ "LEFT OUTER JOIN (SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "					WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "ON( onw_medroom=bmr_code AND bmr_stdate=(SELECT MAX(bmr_stdate) "
			+ "											FROM medroom "
			+ "											WHERE bmr_code=onw_medroom AND bmr_stdate<=onw_ch_date) "
			+ "												AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "WHERE 0=0 AND NOT(onw_kind LIKE '9%')  "
			+ "AND onw_class LIKE '1%' AND (onw_kind LIKE '1%' OR onw_kind LIKE '3%' OR onw_kind LIKE '5%' OR onw_kind LIKE '_3')  "
			+ "]]>"
			+ "<if test=\"date != null and date != ''\">"
			+ "AND onw_ch_date=#{date} "
			+ "</if>"
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND bmr_name=#{room_name} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ "AND onw_name LIKE '%${name}%' "
			+ "</if>"			
			+ "<if test=\"sort != null and sort != '' and sort == 'name-asc'\">"
			+ "ORDER BY onw_name ASC "
			+ "</if>"
			+ "<if test=\"sort != null and sort != '' and sort == 'name-desc'\">"
			+ "ORDER BY onw_name DESC "
			+ "</if>"
			+ "<if test=\"sort != null and sort != '' and sort == 'time-asc'\">"
			+ "ORDER BY onw_time ASC "
			+ "</if>"
			+ "<if test=\"sort != null and sort != '' and sort == 'time-desc'\">"
			+ "ORDER BY onw_time DESC "
			+ "</if>"
			+ "<if test=\"sort == null or sort == ''\">"
			+ "ORDER BY onw_time ASC "
			+ "</if>"
			+ "</script>")
	public List<PatientSearchOutCompleteDataVO> selectPatientSearchOutComplete2(PatientSearchParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT COUNT(*) AS consent_count FROM emrchart AS ec LEFT OUTER JOIN emrsheet_list AS esl ON ec.oec_sid=esl.bes_id "
			+ "WHERE 0=0 "
			+ "AND esl.bes_kind in (80,99) AND esl.bes_use='1' "
			+ "AND (ec.oec_state='S' OR ec.oec_state='E')   "
			+ "AND ec.oec_ptno=#{ptno} AND ec.oec_date=#{date} "
			+ "]]>"
			+ "</script>")
	public int countConsentCountComplete(String ptno, String date) throws Exception;	
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT ois_byungdong,ois_room,ois_regno,oip_in_date,ois_ptno,ois_name,ois_resno, ois_age,ois_sex,ois_reg_ref,ois_medroom,ois_kwa, "
			+ "(SELECT bji_name FROM jonginfo WHERE bji_code=ois_jogubun ), bmr_name,bmr_docname,bmr_kwanm "
			+ "FROM ipwon, ipst "
			+ "LEFT OUTER JOIN (SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "					WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "ON( bmr_code=ois_medroom AND bmr_stdate= (SELECT MAX(bmr_stdate) "
			+ "											FROM medroom "
			+ "											WHERE bmr_code=ois_medroom AND bmr_stdate<=DATEFORMAT(GETDATE(), 'yyyymmdd')) "
			+ "											AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "]]>"
			+ "WHERE oip_regno=ois_regno AND oip_ptno =ois_ptno  "
			+ "<if test=\"byungdong != null and byungdong != ''\">"
			+ "AND ois_byungdong=#{byungdong} "
			+ "</if>"
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND bmr_name=#{room_name} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ "AND ois_name LIKE '%${name}%' "
			+ "</if>"	
			+ "ORDER BY ois_byungdong, ois_room   "
			+ "</script>")
	public List<PatientSearchInJaewonDataVO> selectPatientSearchInJaewon(PatientSearchParamVO vo) throws Exception;	
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT och_byungdong,och_room,oip_regno,oip_in_date,oip_out_date,oip_out_time,oip_ptno, oip_name,oip_resno,oip_age,oip_sex,oip_medroom,oip_kwa,och_jogubun, "
			+ "(SELECT bji_name FROM jonginfo WHERE bji_code=och_jogubun), bmr_name,bmr_docname,bmr_kwanm  "
			+ "FROM ipwon "
			+ "LEFT OUTER JOIN (SELECT TOP 1 och_regno,och_seq,och_byungdong,och_room,och_jogubun,bmr_name,bmr_docname,bmr_kwanm  "
			+ "					FROM changehis "
			+ "					LEFT OUTER JOIN (SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate FROM medroom "
			+ "									WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "					AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "					ON( bmr_code=och_medroom AND bmr_stdate= (SELECT MAX(bmr_stdate) FROM medroom WHERE bmr_code=och_medroom AND bmr_stdate<=och_st_date)) AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "AS chgroom( och_regno,och_seq,och_byungdong,och_room,och_jogubun,bmr_name,bmr_docname,bmr_kwanm ) "
			+ "ON ( och_regno=oip_regno AND och_seq=(SELECT MAX(och_seq) FROM changehis WHERE och_regno=oip_regno)) "
			+ "]]>"
			+ "WHERE 0=0  "
			+ "AND oip_out_date BETWEEN #{start_date} AND #{end_date} "
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND bmr_name=#{room_name} "
			+ "</if>"
			+ "ORDER BY och_byungdong, och_room  "
			+ "</script>")
	public List<PatientSearchInToewonDataVO> selectPatientSearchInToewon(PatientSearchParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ " SELECT DISTINCT bpt_ptno as ptno,bpt_name as name,bpt_resno as resno,bpt_telno as telno,"
			+ "		bpt_hpno as hpno,bpt_cen as cen,bpt_jogubun as jogubun,bpt_sex as sex, bpt_mihonmo as mihonmo,"
			+ "		bpt_enddt as enddt,onw_ch_date as ch_date,onw_medroom, bmr_docname as medroom_docname, "
			+ "calage(bpt_cen + substr(bpt_resno, 1, 6),today()) as age, "
			+ "		(SELECT bji_name FROM jonginfo WHERE bji_code=bpt_jogubun) as bji_name,bmr_code as medroom_code,bmr_name as medroom_name "
			+ "FROM patient "
			+ "LEFT OUTER JOIN "
			+ "(SELECT onw_ptno,onw_ch_date,onw_medroom FROM naewon a WHERE onw_ch_date=(SELECT MAX(onw_ch_date) "
			+ "																				FROM naewon WHERE onw_ptno=a.onw_ptno)) "
			+ "AS NW(onw_ptno,onw_ch_date,onw_medroom) "
			+ "ON (onw_ptno=bpt_ptno) "
			+ "LEFT OUTER JOIN (SELECT bmr_code,bmr_name,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate "
			+ "					FROM medroom "
			+ "					WHERE bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y') ) "
			+ "AS med( bmr_code,bmr_name ,bmr_docname,bmr_kwanm,bmr_hosnum,bmr_stdate ) "
			+ "ON( onw_medroom=bmr_code AND bmr_stdate=(SELECT MAX(bmr_stdate) FROM medroom "
			+ "											WHERE bmr_code=onw_medroom AND bmr_stdate<=onw_ch_date) "
			+ "											AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bmr_hosnum=bhi_hosnum and bhi_usechk='Y')) "
			+ "]]>"
			+ "WHERE 0=0  "
			+ "<if test=\"ptno != null and ptno != ''\">"
			+ "AND bpt_ptno = #{ptno} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ "AND bpt_name LIKE '%${name}%' "
			+ "</if>"
			+ "<if test=\"medroom != null and medroom != ''\">"
			+ "AND onw_medroom = #{medroom} "
			+ "</if>"
			+ "ORDER BY bpt_name "
			+ "</script>")
	public List<PatientSearchDataVO> selectPatientSearch(PatientSearchParamVO vo) throws Exception;
}
