package kr.ondoc.mapper.sybaseemr.penchart;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import kr.ondoc.domain.sybase.penchart.AddTreeParamVO;
import kr.ondoc.domain.sybase.penchart.ChartTreeParamVO;

public interface DbTreeMapper {
	@Select("<script>" 
			+ "SELECT depth1_id, depth1_name, depth2_id, depth2_name, depth3_id, depth3_name, oec_time FROM (" 
			+ "SELECT bec_seq, bec_parid AS 'depth1_id' ,"
			+ "(SELECT bec_seq FROM emrchart_list WHERE bec_id=eml.bec_parid) as parseq, "
			+ "(CASE WHEN parseq is NULL then bec_seq Else parseq END) as par_seq, "
			+ "(SELECT TOP 1 bec_name FROM emrchart_list WHERE bec_id=eml.bec_parid) AS 'depth1_name', "
			+ "bec_id AS 'depth2_id', bec_name AS 'depth2_name'," 
			+ "oec_seq AS 'depth3_id', (CASE WHEN oec_time is NULL then SUBSTRING(oec_cdate, 12, 9) Else oec_time END) as oec_time, "
			+ "(CASE WHEN oec_date is NULL then LEFT(CONVERT(varchar, getdate(), 120), 10)  ELSE oec_date END)  AS 'depth3_name'FROM emrchart AS em "
			+ "LEFT OUTER JOIN emrchart_list AS eml " 
			+ "ON bec_id=oec_cid " + "LEFT OUTER JOIN emrchart_right AS emr "
			+ "ON xer_id=oec_cid AND xer_inout=oec_inout " 
			+ "LEFT OUTER JOIN emrsheet_list AS ems ON oec_sid=bes_id " 
			+ "WHERE oec_use='1' AND xer_view='1' "
			+ "<if test=\"seqs == null or seqs == ''\">" 
			+ "<![CDATA[" 
			+ " AND oec_state<>'N' " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ " AND (oec_state<>'N' OR oec_seq in (${seqs})) " 
			+ "]]>" 
			+ "</if>"
			+ "AND oec_ptno = #{oec_ptno} " 
			+ "AND oec_inout = #{oec_inout} " 
			+ "AND xer_uid = #{xer_uid} " 
			
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bes_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bes_kind not in ('80', '99') " 
			+ "</if>"

			+ "<if test=\"start_date != null and start_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{start_date} <= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"start_date != null and start_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{start_date} <= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{end_date} >= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{end_date} >= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ ") AS temp "

			+ "ORDER BY  par_seq, bec_seq, depth1_id, depth2_id, depth3_name DESC, oec_time DESC" 
			+ "</script>")
	public List<ChartTreeParamVO> selectChartTree(ChartTreeParamVO vo) throws Exception;
	
	@Select("<script>" 
			+ "SELECT  depth1_id, depth1_name FROM (" 
			+ "SELECT bec_parid AS 'depth1_id' ,"
			+ "(SELECT TOP 1 bec_name FROM emrchart_list WHERE bec_id=eml.bec_parid) AS 'depth1_name', "
			+ "bec_id AS 'depth2_id', bec_name AS 'depth2_name'," + "oec_seq AS 'depth3_id',"
			+ "(CASE WHEN oec_date is NULL then LEFT(CONVERT(varchar, getdate(), 120), 10)  ELSE oec_date END)  AS 'depth3_name'FROM emrchart AS em "
			+ "LEFT OUTER JOIN emrchart_list AS eml " 
			+ "ON bec_id=oec_cid " 
			+ "LEFT OUTER JOIN emrchart_right AS emr "
			+ "ON xer_id=oec_cid AND xer_inout=oec_inout "
			+ "LEFT OUTER JOIN emrsheet_list AS ems ON oec_sid=bes_id " 
			+ "WHERE oec_use='1' AND xer_view='1' "
			+ "<if test=\"seqs == null or seqs == ''\">" 
			+ "<![CDATA[" 
			+ " AND oec_state<>'N' " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ " AND (oec_state<>'N' OR oec_seq in (${seqs})) " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"oec_ptno != null and oec_ptno != ''\">" 
			+ "AND oec_ptno = #{oec_ptno} " 
			+ "</if>"
			+ "<if test=\"oec_inout != null and oec_inout != ''\">" 
			+ "AND oec_inout = #{oec_inout} " 
			+ "</if>"

			+ "<if test=\"xer_uid != null and xer_uid != ''\">" 
			+ "AND xer_uid = #{xer_uid} " 
			+ "</if>"
			
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bes_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bes_kind not in ('80', '99') " 
			+ "</if>"
			
			
			+ "<if test=\"start_date != null and start_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{start_date} <= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"start_date != null and start_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{start_date} <= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{end_date} >= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{end_date} >= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ ") AS temp GROUP BY depth1_id, depth1_name " 
			+ "ORDER BY depth1_id" 
			+ "</script>")
	public List<ChartTreeParamVO> selectChartTree1Depth(ChartTreeParamVO vo) throws Exception;

			@Select("<script>" 
			+ "SELECT min(oec_date)  as oec_date, min(oec_time)  as oec_time, min(bec_seq)  as bec_seq, depth2_id, depth2_name, min(depth3_id) as depth3_id FROM (" 
			+ "SELECT oec_date, oec_time, bec_seq, bec_parid AS 'depth1_id' ,"
			+ "(SELECT TOP 1 bec_name FROM emrchart_list WHERE bec_id=eml.bec_parid) AS 'depth1_name', "
			+ "bec_id AS 'depth2_id', bec_name AS 'depth2_name'," 
			+ "oec_seq AS 'depth3_id',"
			+ "(CASE WHEN oec_date is NULL then LEFT(CONVERT(varchar, getdate(), 120), 10)  ELSE oec_date END)  AS 'depth3_name'FROM emrchart AS em "
			+ "LEFT OUTER JOIN emrchart_list AS eml " 
			+ "ON bec_id=oec_cid " 
			+ "LEFT OUTER JOIN emrchart_right AS emr "
			+ "ON xer_id=oec_cid AND xer_inout=oec_inout " 
			+ "LEFT OUTER JOIN emrsheet_list AS ems ON oec_sid=bes_id " 
			+ "WHERE oec_use='1' AND xer_view='1' "
			+ "<if test=\"seqs == null or seqs == ''\">" 
			+ "<![CDATA[" 
			+ " AND oec_state<>'N' " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ " AND (oec_state<>'N' OR oec_seq in (${seqs})) " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"oec_ptno != null and oec_ptno != ''\">" 
			+ "AND oec_ptno = #{oec_ptno} " 
			+ "</if>"
			+ "<if test=\"oec_inout != null and oec_inout != ''\">" 
			+ "AND oec_inout = #{oec_inout} " 
			+ "</if>"

			+ "<if test=\"xer_uid != null and xer_uid != ''\">" 
			+ "AND xer_uid = #{xer_uid} " 
			+ "</if>"
			
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bes_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bes_kind not in ('80', '99') " 
			+ "</if>"

			+ "<if test=\"start_date != null and start_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{start_date} <= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"start_date != null and start_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{start_date} <= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{end_date} >= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{end_date} >= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ ") AS temp GROUP BY depth1_id, depth2_id, depth2_name HAVING depth1_id=#{depth1_id}"
			+ "ORDER BY bec_seq, oec_date, oec_time, depth1_id, depth2_id, depth3_id" 
			+ "</script>")
	public List<ChartTreeParamVO> selectChartTree2Depth(ChartTreeParamVO vo) throws Exception;

			@Select("<script>" 
			+ "SELECT depth2_id, depth3_id, depth3_name FROM (" 
			+ "SELECT bec_parid AS 'depth1_id' ,"
			+ "(SELECT TOP 1 bec_name FROM emrchart_list WHERE bec_id=eml.bec_parid) AS 'depth1_name', "
			+ "bec_id AS 'depth2_id', bec_name AS 'depth2_name'," 
			+ "oec_seq AS 'depth3_id',"
			+ "(CASE WHEN oec_date is NULL then LEFT(CONVERT(varchar, getdate(), 120), 10)  ELSE oec_date END)  AS 'depth3_name'FROM emrchart AS em "
			+ "LEFT OUTER JOIN emrchart_list AS eml " 
			+ "ON bec_id=oec_cid " + "LEFT OUTER JOIN emrchart_right AS emr "
			+ "ON xer_id=oec_cid AND xer_inout=oec_inout " 
			+ "LEFT OUTER JOIN emrsheet_list AS ems ON oec_sid=bes_id " 
			+ "WHERE oec_use='1' AND xer_view='1' "
			+ "<if test=\"seqs == null or seqs == ''\">" 
			+ "<![CDATA[" 
			+ " AND oec_state<>'N' " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ " AND (oec_state<>'N' OR oec_seq in (${seqs})) " 
			+ "]]>" 
			+ "</if>"
			+ "AND oec_ptno = #{oec_ptno} " 
			+ "AND oec_inout = #{oec_inout} " 
			+ "AND xer_uid = #{xer_uid} " 
			
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bes_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bes_kind not in ('80', '99') " 
			+ "</if>"

			+ "<if test=\"start_date != null and start_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{start_date} <= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"start_date != null and start_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{start_date} <= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{end_date} >= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{end_date} >= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ ") AS temp GROUP BY depth1_id, depth2_id, depth3_id, depth3_name "
			+ "<if test=\"depth2_id != null and depth2_id != ''\">" 
			+ "<![CDATA["
			+ "HAVING depth2_id=#{depth2_id}"
			+ "]]>" 
			+ "</if>"
			+ "ORDER BY depth1_id, depth2_id, depth3_name DESC" 
			+ "</script>")
	public List<ChartTreeParamVO> selectChartTree3Depth(ChartTreeParamVO vo) throws Exception;
			
			@Select("<script>" 
			+ "SELECT depth2_id FROM (" 
			+ "SELECT bec_parid AS 'depth1_id' ,"
			+ "(SELECT TOP 1 bec_name FROM emrchart_list WHERE bec_id=eml.bec_parid) AS 'depth1_name', "
			+ "bec_id AS 'depth2_id', bec_name AS 'depth2_name'," 
			+ "oec_seq AS 'depth3_id',"
			+ "(CASE WHEN oec_date is NULL then LEFT(CONVERT(varchar, getdate(), 120), 10)  ELSE oec_date END)  AS 'depth3_name'FROM emrchart AS em "
			+ "LEFT OUTER JOIN emrchart_list AS eml " 
			+ "ON bec_id=oec_cid " + "LEFT OUTER JOIN emrchart_right AS emr "
			+ "ON xer_id=oec_cid AND xer_inout=oec_inout " 
			+ "LEFT OUTER JOIN emrsheet_list AS ems ON oec_sid=bes_id " 
			+ "WHERE oec_use='1' AND xer_view='1' "
			+ "<if test=\"seqs == null or seqs == ''\">" 
			+ "<![CDATA[" 
			+ " AND oec_state<>'N' " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ " AND (oec_state<>'N' OR oec_seq in (${seqs})) " 
			+ "]]>" 
			+ "</if>"
			+ "AND oec_ptno = #{oec_ptno} " 
			+ "AND oec_inout = #{oec_inout} " 
			+ "AND xer_uid = #{xer_uid} " 
			
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bes_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bes_kind not in ('80', '99') " 
			+ "</if>"

			+ "<if test=\"start_date != null and start_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{start_date} <= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"start_date != null and start_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{start_date} <= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{end_date} >= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{end_date} >= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ ") AS temp GROUP BY depth1_id, depth2_id, depth3_id, depth3_name "
			+ "<if test=\"depth2_id != null and depth2_id != ''\">" 
			+ "<![CDATA["
			+ "HAVING depth2_id=#{depth2_id}"
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seq != null and seq != ''\">" 
			+ "<![CDATA["
			+ "HAVING depth3_id=#{seq}"
			+ "]]>" 
			+ "</if>"
			+ "ORDER BY depth1_id, depth2_id, depth3_name DESC" 
			+ "</script>")
	public String selectChartTree3DepthNextSheetParentId(ChartTreeParamVO vo) throws Exception;
			
	@Select("<script>" 
			+ "SELECT TOP 1 depth3_id FROM (" 
			+ "SELECT bec_parid AS 'depth1_id' ,"
			+ "(SELECT TOP 1 bec_name FROM emrchart_list WHERE bec_id=eml.bec_parid) AS 'depth1_name', "
			+ "bec_id AS 'depth2_id', bec_name AS 'depth2_name'," 
			+ "oec_seq AS 'depth3_id',"
			+ "(CASE WHEN oec_date is NULL then LEFT(CONVERT(varchar, getdate(), 120), 10)  ELSE oec_date END)  AS 'depth3_name'FROM emrchart AS em "
			+ "LEFT OUTER JOIN emrchart_list AS eml " 
			+ "ON bec_id=oec_cid " + "LEFT OUTER JOIN emrchart_right AS emr "
			+ "ON xer_id=oec_cid AND xer_inout=oec_inout " 
			+ "LEFT OUTER JOIN emrsheet_list AS ems ON oec_sid=bes_id " 
			+ "WHERE oec_use='1' AND xer_view='1' "
			+ "<if test=\"seqs == null or seqs == ''\">" 
			+ "<![CDATA[" 
			+ " AND oec_state<>'N' " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ " AND (oec_state<>'N' OR oec_seq in (${seqs})) " 
			+ "]]>" 
			+ "</if>"
			+ "AND oec_ptno = #{oec_ptno} " 
			+ "AND oec_inout = #{oec_inout} " 
			+ "AND xer_uid = #{xer_uid} " 
			
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bes_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bes_kind not in ('80', '99') " 
			+ "</if>"

			+ "<if test=\"start_date != null and start_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{start_date} <= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"start_date != null and start_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{start_date} <= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and (seqs == null or seqs == '')\">" 
			+ "<![CDATA["
			+ "AND #{end_date} >= oec_date   " 
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"end_date != null and end_date != '' and seqs != null and seqs != ''\">" 
			+ "<![CDATA["
			+ "AND (#{end_date} >= oec_date OR oec_seq in (${seqs}))  " 
			+ "]]>" 
			+ "</if>"
			+ ") AS temp GROUP BY depth1_id, depth2_id, depth3_id, depth3_name "
			+ "<if test=\"depth2_id != null and depth2_id != ''\">" 
			+ "<![CDATA["
			+ "HAVING depth2_id=#{depth2_id} AND depth3_id<#{seq} "
			+ "]]>" 
			+ "</if>"
			+ "<if test=\"depth2_id == null and seq != null and seq != ''\">" 
			+ "<![CDATA["
			+ "HAVING depth3_id<#{seq}"
			+ "]]>" 
			+ "</if>"
			+ "ORDER BY depth1_id, depth2_id, depth3_name DESC" 
			+ "</script>")
	public String selectChartTree3DepthNextSheet(ChartTreeParamVO vo) throws Exception;
			
//	@Select("<script>" 
//			+ "<![CDATA["
//			+ "SELECT (SELECT bes_seq FROM emrsheet_list WHERE bes_id=a.bes_parid) as parseq,     "
//			+ "(CASE WHEN parseq is NULL then bes_seq Else parseq END) as par_seq, * FROM emrsheet_list a "
//			+ "LEFT OUTER JOIN (SELECT be2_no,xer_edit FROM emrchart_list2, emrchart_right "
//			+ "WHERE xer_inout=#{bes_inout} AND xer_uid = #{xer_uid} AND xer_id=be2_id) AS emrright(be2_no,xer_edit) "
//			+ "ON (be2_no= bes_id) "
//			+ "WHERE bes_use = '1' AND bes_inout = #{bes_inout} "
//			+ "]]>" 
//			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
//			+ "AND bes_kind in (${bes_kind}) " 
//			+ "</if>"
//			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
//			+ "AND bes_kind not in ('80', '99') " 
//			+ "</if>"
//			+ "<![CDATA["
//			+ "AND (xer_edit = '1' OR (xer_edit is NULL and bes_parid = 0)) "
//			+ "AND bes_depth = '1' "
//			+ "]]>" 
//			+ "ORDER BY bes_seq  "
//			+ "</script>")
//	public List<AddTreeParamVO> selectAddTree1Depth(AddTreeParamVO vo) throws Exception;
	
	@Select("<script>" 
			+ "<![CDATA["
			+ "SELECT (SELECT bec_seq FROM emrchart_list                                                   "
			+ "         WHERE bec_id=a.bec_parid) as parseq,                                               "
			+ "       (CASE                                                                                "
			+ "            WHEN parseq is NULL then bec_seq                                                "
			+ "            Else parseq                                                                     "
			+ "        END) as bes_id, bec_name AS bes_name, bec_use, bec_ccnt, bes_use, be2_no             "
			+ "  FROM emrchart_list a LEFT OUTER JOIN (SELECT be2_id,be2_no,xer_edit,bes_name,bes_use FROM emrchart_right, emrchart_list2 LEFT OUTER JOIN emrsheet_list ON ( bes_id = be2_no) "
			+ "                                         WHERE xer_inout=#{bes_inout}                       "
			+ "                                           AND xer_uid  = #{xer_uid}                 "
			+ "                                           AND xer_id=be2_id)                               "
			+ "                            AS emrright(be2_id, be2_no,xer_edit,bes_name,bes_use)           "
			+ "                            ON         (be2_id= bec_id)                                     "
			+ " WHERE bec_inout=#{bes_inout} "
			+ "   AND bec_use  ='1' "
			+ "]]>" 
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bec_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bec_kind not in ('80', '99') " 
			+ "</if>"
			+ "<![CDATA["
			+ "   AND (xer_edit='1' OR (xer_edit is NULL and bec_parid=0) )     "
			+ "   and parseq is null "
			+ "]]>" 
			+ "ORDER BY bes_id,bec_depth,bec_seq  "
			+ "</script>")
	public List<AddTreeParamVO> selectAddTree1Depth(AddTreeParamVO vo) throws Exception;
	
//	@Select("<script>" 
//			+ "<![CDATA["
//			+ "SELECT (SELECT bes_seq FROM emrsheet_list WHERE bes_id=a.bes_parid) as parseq,     "
//			+ "(CASE WHEN parseq is NULL then bes_seq Else parseq END) as par_seq, * FROM emrsheet_list a "
//			+ "LEFT OUTER JOIN (SELECT be2_no,xer_edit FROM emrchart_list2, emrchart_right "
//			+ "WHERE xer_inout=#{bes_inout} AND xer_uid = #{xer_uid} AND xer_id=be2_id) AS emrright(be2_no,xer_edit) "
//			+ "ON (be2_no= bes_id) "
//			+ "WHERE bes_use = '1' AND bes_inout = #{bes_inout} "
//			+ "]]>" 
//			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
//			+ "AND bes_kind in (${bes_kind}) " 
//			+ "</if>"
//			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
//			+ "AND bes_kind not in ('80, 99') " 
//			+ "</if>"
//			+ "<![CDATA["
//			+ "AND (xer_edit = '1' OR (xer_edit is NULL and bes_parid = 0)) "
//			+ "AND bes_depth = '2' "
//			+ "AND bes_parid = #{bes_id} "
//			+ "]]>" 
//			+ "ORDER BY bes_seq  "
//			+ "</script>")
//	public List<AddTreeParamVO> selectAddTree2Depth(AddTreeParamVO vo) throws Exception;
	
	@Select("<script>" 
			+ "<![CDATA["
			+ "SELECT (SELECT bec_seq FROM emrchart_list                                                   "
			+ "         WHERE bec_id=a.bec_parid) as parseq,                                               "
			+ "       (CASE                                                                                "
			+ "            WHEN parseq is NULL then bec_seq                                                "
			+ "            Else parseq                                                                     "
			+ "        END) as bes_id, bec_name AS bes_name, bec_use, bec_ccnt, bes_use, be2_no             "
			+ "  FROM emrchart_list a LEFT OUTER JOIN (SELECT be2_id,be2_no,xer_edit,bes_name,bes_use FROM emrchart_right, emrchart_list2 LEFT OUTER JOIN emrsheet_list ON ( bes_id = be2_no) "
			+ "                                         WHERE xer_inout=#{bes_inout}                       "
			+ "                                           AND xer_uid  = #{xer_uid}                 "
			+ "                                           AND xer_id=be2_id)                               "
			+ "                            AS emrright(be2_id, be2_no,xer_edit,bes_name,bes_use)           "
			+ "                            ON         (be2_id= bec_id)                                     "
			+ " WHERE bec_inout=#{bes_inout} "
			+ "   AND bec_use  ='1'  AND bes_use='1' " 
			+ "]]>" 
			+ "<if test=\"bes_kind != null and bes_kind != ''\">" 
			+ "AND bec_kind in (${bes_kind}) " 
			+ "</if>"
			+ "<if test=\"bes_kind == null or bes_kind == ''\">" 
			+ "AND bec_kind not in ('80', '99') " 
			+ "</if>"
			+ "<![CDATA["
			+ "   AND (xer_edit='1' OR (xer_edit is NULL and bec_parid=0) )     "
			+ "   and parseq =  #{bes_id} "
			+ "]]>" 
			+ "ORDER BY bes_id,bec_depth,bec_seq  "
			+ "</script>")
	public List<AddTreeParamVO> selectAddTree2Depth(AddTreeParamVO vo) throws Exception;
}
