package kr.ondoc.mapper.sybase.crm;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import kr.ondoc.domain.sybase.crm.CrmOperationScheduleLimitVO;
import kr.ondoc.domain.sybase.crm.CrmOperationSchedulePatientListVO;
import kr.ondoc.domain.sybase.crm.CrmOperationScheduleVO;
import kr.ondoc.domain.sybase.crm.CrmTotalVO;

public interface CrmOperationScheduleMapper {
	//마이그레이션 하기전 예약된게 있는지 확인
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT COUNT(*) FROM crm_operation_schedule WHERE 0=0 "
			+ "]]>"
			+ "<if test=\"department_idx != null and department_idx != ''\">"
			+ "AND department_idx = #{department_idx} "
			+ "</if>"
			+ "<if test=\"department_number != null and department_number != ''\">"
			+ "AND department_number = #{department_number} "
			+ "</if>"
			+ "<if test=\"schedule_date != null and schedule_date != ''\">"
			+ "AND schedule_date = #{schedule_date} "
			+ "</if>"
			+ "<if test=\"schedule_time != null and schedule_time != ''\">"
			+ "AND schedule_time = #{schedule_time} "
			+ "</if>"
			+ "AND del_yn = 'N' "
			+ "</script>")
	public int countOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "select * from ("
			+ "select operation_schedule_idx AS `idx`, 'reserve' AS `gubun`, department_idx, department_number, schedule_date AS `date`, schedule_time As `time`, item_arr, "
			+ "receptionist_id, counselor_id, therapist_id, doctor_id, reserve_memo AS memo, cancel_memo, del_yn "
			+ "from crm_operation_schedule WHERE ptno = #{ptno} "
			+ "UNION ALL "
			+ "select counsel_idx AS `idx`, 'counsel' AS `gubun`, '' AS department_idx, '' AS department_number, counsel_date AS `date`, substr(write_date, 9, 4) AS `time`, item_arr, "
			+ "receptionist_id, counselor_id, therapist_id, doctor_id, counsel_memo AS memo, '' AS cancel_memo, del_yn "
			+ "from crm_treatement_counsel WHERE del_yn=#{del_yn} AND ptno = #{ptno} "
			+ "UNION ALL "
			+ "select treatement_idx AS `idx`, 'treatement' AS `gubun`, '' AS department_idx, '' AS department_number, treatement_date AS `date`, substr(write_date, 9, 4) AS `time`, item_arr, "
			+ "receptionist_id, counselor_id, therapist_id, doctor_id, treatement_memo AS memo, '' AS cancel_memo, del_yn "
			+ "from crm_treatement WHERE del_yn=#{del_yn} AND ptno = #{ptno})"
			+ "AS temp ORDER BY `date` DESC, `time` DESC "
			+ "]]>"
			+ "</script>")
	public List<CrmTotalVO> selectListTotal(CrmTotalVO vo) throws Exception;		
			
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT pa.bpt_name AS name, pa.bpt_birth As birthday, pa.bpt_yage AS age, pa.bpt_sex AS sex, pa.bpt_jubsumemo AS customer_memo, "
			+ "pa.bpt_hpno AS hpno, pa.bpt_zip AS zip, pa.bpt_addr AS addr, pa.bpt_addr2 AS addr2, "
			+ "operation_schedule_idx, status_idx, department_idx, department_number, setcolor_idx, schedule_date, schedule_time, treatement_time,"
			+ "ptno, receptionist_id, counselor_id, therapist_id, doctor_id, visit_type,"
			+ "sms_send_check, reserve_type, rev_bookingkey, rev_reservationkey, reserve_memo, cancel_memo, item_arr, sms_reserved_id, kakao_group_id "
			+ "FROM crm_operation_schedule AS cos "
			+ "LEFT OUTER JOIN patient AS pa "
			+ "ON cos.ptno=pa.bpt_ptno WHERE 0=0 "
			+ "]]>"
			+ "AND operation_schedule_idx = #{idx} "
			+ "</script>")
	public CrmOperationSchedulePatientListVO selectListOperationScheduleIdx(String idx) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT pa.bpt_name AS name, pa.bpt_birth As birthday, pa.bpt_yage AS age, pa.bpt_sex AS sex, pa.bpt_jubsumemo AS customer_memo, "
			+ "pa.bpt_hpno AS hpno, pa.bpt_zip AS zip, pa.bpt_addr AS addr, pa.bpt_addr2 AS addr2, "
			+ "operation_schedule_idx, status_idx, department_idx, department_number, setcolor_idx, schedule_date, schedule_time, treatement_time,"
			+ "ptno, receptionist_id, counselor_id, therapist_id, doctor_id, visit_type,"
			+ "sms_send_check, reserve_type, rev_bookingkey, rev_reservationkey, reserve_memo, cancel_memo, item_arr, sms_reserved_id, kakao_group_id "
			+ "FROM crm_operation_schedule AS cos "
			+ "LEFT OUTER JOIN patient AS pa "
			+ "ON cos.ptno=pa.bpt_ptno WHERE 0=0 "
			+ "]]>"
			+ "<if test=\"department_idx != null and department_idx != ''\">"
			+ "AND department_idx = #{department_idx} "
			+ "</if>"
			+ "<if test=\"schedule_date != null and schedule_date != '' and schedule_date.length  == 8\">"
			+ "AND schedule_date = #{schedule_date} "
			+ "</if>"
			+ "<if test=\"schedule_date != null and schedule_date != '' and schedule_date.length  == 6\">"
			+ "AND schedule_date like '${schedule_date}%' "
			+ "</if>"
			+ "<if test=\"del_yn != null and del_yn != ''\">"
			+ "AND del_yn = #{del_yn} "
			+ "</if>"
			+ "ORDER BY schedule_date, schedule_time, department_idx"
			+ "</script>")
	public List<CrmOperationSchedulePatientListVO> selectListOperationSchedulePatient(CrmOperationSchedulePatientListVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT schedule_time, treatement_time, department_idx, department_number, schedule_date from crm_operation_schedule WHERE 0=0 "
			+ "]]>"
			+ "<if test=\"department_idx != null and department_idx != ''\">"
			+ "AND department_idx = #{department_idx} "
			+ "</if>"
			+ "<if test=\"department_number != null and department_number != ''\">"
			+ "AND department_number = #{department_number} "
			+ "</if>"
			+ "<if test=\"schedule_date != null and schedule_date != ''\">"
			+ "AND schedule_date = #{schedule_date} "
			+ "</if>"
			+ "AND del_yn = 'N' "
			+ "</script>")
	public List<CrmOperationScheduleLimitVO> selectListOperationScheduleLimit(CrmOperationScheduleLimitVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT pa.bpt_name AS name, pa.bpt_birth As birthday, pa.bpt_yage AS age, pa.bpt_sex AS sex, "
			+ "pa.bpt_hpno AS hpno, pa.bpt_zip AS zip, pa.bpt_addr AS addr, pa.bpt_addr2 AS addr2, "
			+ "operation_schedule_idx, status_idx, department_idx, (SELECT department_name FROM crm_department WHERE department_idx=cos.department_idx) AS department_name,"
			+ "department_number, schedule_date, schedule_time, treatement_time,"
			+ "ptno, receptionist_id, counselor_id, therapist_id, doctor_id, visit_type,"
			+ "sms_send_check, reserve_type, rev_bookingkey, rev_reservationkey, reserve_memo, cancel_memo, item_arr, sms_reserved_id, kakao_group_id "
			+ "FROM crm_operation_schedule AS cos "
			+ "LEFT OUTER JOIN patient AS pa "
			+ "ON cos.ptno=pa.bpt_ptno WHERE 0=0 "
			+ "]]>"
			+ "<if test=\"ptno != null and ptno != ''\">"
			+ "AND ptno = #{ptno} "
			+ "</if>"
			+ "<if test=\"del_yn != null and del_yn != ''\">"
			+ "AND del_yn = #{del_yn} "
			+ "</if>"
			+ "ORDER BY operation_schedule_idx DESC"
			+ "</script>")
	public List<CrmOperationScheduleVO> selectListOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT pa.bpt_name AS name, pa.bpt_birth As birthday, pa.bpt_yage AS age, pa.bpt_sex AS sex, "
			+ "pa.bpt_hpno AS hpno, pa.bpt_zip AS zip, pa.bpt_addr AS addr, pa.bpt_addr2 AS addr2, "
			+ "operation_schedule_idx, status_idx, department_idx, (SELECT department_name FROM crm_department WHERE department_idx=cos.department_idx) AS department_name,"
			+ "department_number, schedule_date, schedule_time, treatement_time,"
			+ "ptno, receptionist_id, counselor_id, therapist_id, doctor_id, visit_type,"
			+ "sms_send_check, reserve_type, rev_bookingkey, rev_reservationkey, reserve_memo, cancel_memo, item_arr, sms_reserved_id, kakao_group_id "
			+ "FROM crm_operation_schedule AS cos "
			+ "LEFT OUTER JOIN patient AS pa "
			+ "ON cos.ptno=pa.bpt_ptno WHERE 0=0 "
			+ "]]>"
			+ "<if test=\"ptno != null and ptno != ''\">"
			+ "AND ptno = #{ptno} "
			+ "</if>"
			+ "<if test=\"del_yn != null and del_yn != ''\">"
			+ "AND del_yn = #{del_yn} "
			+ "</if>"
			+ "<if test=\"operation_schedule_idx != null and operation_schedule_idx != ''\">"
			+ "AND operation_schedule_idx = #{operation_schedule_idx} "
			+ "</if>"
			+ "ORDER BY operation_schedule_idx DESC"
			+ "</script>")
	public CrmOperationScheduleVO selectOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Select("<script>"
			+ "SELECT MAX(operation_schedule_idx) FROM crm_operation_schedule"
			+ "</script>")
	public String selectMaxIdx() throws Exception;
	
	@Insert("<script>"
			+ "INSERT INTO crm_operation_schedule ("
			+ "status_idx, department_idx, department_number, setcolor_idx, schedule_date, schedule_time, treatement_time, "
			+ "ptno, receptionist_id, counselor_id, therapist_id, doctor_id, visit_type, "
			+ "sms_send_check, reserve_type, rev_bookingkey, rev_reservationkey, reserve_memo, item_arr, sms_reserved_id, kakao_group_id,"
			+ "write_date, "
			+ "write_id) "
			+ "VALUES ( "
			+ "#{status_idx}, #{department_idx}, #{department_number}, #{setcolor_idx}, #{schedule_date}, #{schedule_time}, #{treatement_time}, "
			+ "#{ptno}, #{receptionist_id}, #{counselor_id}, #{therapist_id}, #{doctor_id}, #{visit_type}, "
			+ "#{sms_send_check}, #{reserve_type}, #{rev_bookingkey}, #{rev_reservationkey}, #{reserve_memo}, #{item_arr}, #{sms_reserved_id}, #{kakao_group_id}, "
			+ "CONVERT(VARCHAR(8), GETDATE(), 112) + REPLACE(CONVERT(VARCHAR(8), GETDATE(), 108), ':', ''), "
			+ "#{write_id})"
			+ "</script>")
	public void insertOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Update("<script>"
			+ "UPDATE crm_operation_schedule SET "
			+ "operation_schedule_idx = operation_schedule_idx "
			+ "<if test=\"status_idx != null and status_idx != ''\">"
			+ ",status_idx = #{status_idx} "
			+ "</if>"
			+ "<if test=\"department_idx != null and department_idx != ''\">"
			+ ",department_idx = #{department_idx} "
			+ "</if>"
			+ "<if test=\"department_number != null and department_number != ''\">"
			+ ",department_number = #{department_number} "
			+ "</if>"
			+ "<if test=\"setcolor_idx != null and setcolor_idx != ''\">"
			+ ",setcolor_idx = #{setcolor_idx} "
			+ "</if>"
			+ "<if test=\"schedule_date != null and schedule_date != ''\">"
			+ ",schedule_date = #{schedule_date} "
			+ "</if>"
			+ "<if test=\"schedule_time != null and schedule_time != ''\">"
			+ ",schedule_time = #{schedule_time} "
			+ "</if>"
			+ "<if test=\"treatement_time != null and treatement_time != ''\">"
			+ ",treatement_time = #{treatement_time} "
			+ "</if>"
			+ "<if test=\"ptno != null and ptno != ''\">"
			+ ",ptno = #{ptno} "
			+ "</if>"
			+ "<if test=\"receptionist_id != null and receptionist_id != ''\">"
			+ ",receptionist_id = #{receptionist_id} "
			+ "</if>"
			+ "<if test=\"counselor_id != null and counselor_id != ''\">"
			+ ",counselor_id = #{counselor_id} "
			+ "</if>"
			+ "<if test=\"therapist_id != null and therapist_id != ''\">"
			+ ",therapist_id = #{therapist_id} "
			+ "</if>"
			+ "<if test=\"doctor_id != null and doctor_id != ''\">"
			+ ",doctor_id = #{doctor_id} "
			+ "</if>"
			+ "<if test=\"visit_type != null and visit_type != ''\">"
			+ ",visit_type = #{visit_type} "
			+ "</if>"
			+ "<if test=\"sms_send_check != null and sms_send_check != ''\">"
			+ ",sms_send_check = #{sms_send_check} "
			+ "</if>"
			+ "<if test=\"reserve_type != null and reserve_type != ''\">"
			+ ",reserve_type = #{reserve_type} "
			+ "</if>"
			+ "<if test=\"rev_bookingkey != null and rev_bookingkey != ''\">"
			+ ",rev_bookingkey = #{rev_bookingkey} "
			+ "</if>"
			+ "<if test=\"rev_reservationkey != null and rev_reservationkey != ''\">"
			+ ",rev_reservationkey = #{rev_reservationkey} "
			+ "</if>"
			+ "<if test=\"reserve_memo != null and reserve_memo != ''\">"
			+ ",reserve_memo = #{reserve_memo} "
			+ "</if>"
			+ "<if test=\"cancel_memo != null and cancel_memo != ''\">"
			+ ",cancel_memo = #{cancel_memo} "
			+ "</if>"
			+ "<if test=\"item_arr != null and item_arr != ''\">"
			+ ",item_arr = #{item_arr} "
			+ "</if>"
			+ "<if test=\"sms_reserved_id != null\">"
			+ ",sms_reserved_id = #{sms_reserved_id} "
			+ "</if>"
			+ "<if test=\"kakao_group_id != null\">"
			+ ",kakao_group_id = #{kakao_group_id} "
			+ "</if>"
			+ "<if test=\"del_yn != null and del_yn != ''\">"
			+ ",del_yn = #{del_yn} "
			+ "</if>"
			+ "<if test=\"modify_id != null and modify_id != ''\">"
			+ ",modify_date = CONVERT(VARCHAR(8), GETDATE(), 112) + REPLACE(CONVERT(VARCHAR(8), GETDATE(), 108), ':', '') "
			+ ",modify_id = #{modify_id} "
			+ "</if>"
			+ "WHERE 0=0 "
			+ "AND operation_schedule_idx = #{operation_schedule_idx}"
			+ "</script>")
	public void updateOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Update("<script>"
			+ "UPDATE crm_operation_schedule SET "
			+ "operation_schedule_idx = operation_schedule_idx "
			+ " ,del_date = null "
			+ " ,del_id = null "
			+ " ,cancel_memo = null "
			+ " ,del_yn = 'N' "
			+ "<if test=\"modify_id != null and modify_id != ''\">"
			+ ",modify_date = CONVERT(VARCHAR(8), GETDATE(), 112) + REPLACE(CONVERT(VARCHAR(8), GETDATE(), 108), ':', '') "
			+ ",modify_id = #{modify_id} "
			+ "</if>"
			+ "WHERE 0=0 "
			+ "AND operation_schedule_idx = #{operation_schedule_idx}"
			+ "</script>")
	public void restoreOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Delete("<script>"
			+ "UPDATE crm_operation_schedule SET "
			+ " del_yn = 'Y', "
			+ " del_date = CONVERT(VARCHAR(8), GETDATE(), 112) + REPLACE(CONVERT(VARCHAR(8), GETDATE(), 108), ':', ''), "
			+ " cancel_memo = #{cancel_memo}, "
			+ " del_id = #{del_id} "
			+ "WHERE 0=0  "
			+ "AND operation_schedule_idx=#{operation_schedule_idx} "
			+ "</script>")
	public void deleteOperationSchedule(CrmOperationScheduleVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT MAX(CNT) FROM (\r\n"
			+ "SELECT COUNT(*) AS CNT FROM crm_treatement_counsel WHERE del_yn='N' AND operation_schedule_idx = #{idx} "
			+ "UNION\r\n"
			+ "SELECT COUNT(*) AS CNT FROM crm_treatement WHERE del_yn='N' AND operation_schedule_idx = #{idx} "
			+ "UNION\r\n"
			+ "SELECT COUNT(*) AS CNT FROM crm_treatement_payment WHERE del_yn='N' AND operation_schedule_idx = #{idx} "
			+ ") AS temp "
			+ "]]>"
			+ "</script>")
	public int cntReserveRelation(String idx) throws Exception;
}
