package kr.ondoc.mapper.sybase.crm;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import kr.ondoc.domain.sybase.crm.CrmOnlineReserveMedroomVO;
import kr.ondoc.domain.sybase.crm.CrmRevptNaverVO;

public interface CrmOnlineReserveMapper {
	//온라인예약 진료실 설정을 위해 진료실 정보 가져오기 crm 부서는 구분을 위해 crm_를 붙임
	@Select("<script>"
			+ "<![CDATA["
			+ "select 'crm_' || department_idx AS examinationRoomKey, department_name AS name from crm_department "
			+ "WHERE use_yn='Y'AND del_yn='N' "
			+ "UNION ALL "
			+ "select bmr_code AS examinationRoomKey, bmr_name AS name from medroom "
			+ "WHERE bmr_use='Y' AND bmr_hosnum=(SELECT TOP 1 bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y') "
			+ "]]>"
			+ "</script>")
	public List<CrmOnlineReserveMedroomVO> selectListOnlineReserveMedroom() throws Exception;
	
	@Select("<script>"
			+ "SELECT * from revpt_naver "
			+ "WHERE 0=0 "
			+ "<if test=\"rev_confirm != null and rev_confirm != ''\">"
			+ "AND (rev_confirm = #{rev_confirm} OR rev_confirm = 'S') "
			+ "</if>"
			+ "AND rev_reservationkey like 'crm_%' "
			+ "</script>")
	public List<CrmRevptNaverVO> selectRevptNaver(CrmRevptNaverVO vo) throws Exception;
	
	@Update("<script>"
			+ "UPDATE revpt_naver SET "
			+ "rev_seq = rev_seq "
			+ "<if test=\"rev_reservationkey != null and rev_reservationkey != ''\">"
			+ ",rev_reservationkey = #{rev_reservationkey} "
			+ "</if>"
			+ "<if test=\"rev_bookingkey != null and rev_bookingkey != ''\">"
			+ ",rev_bookingkey = #{rev_bookingkey} "
			+ "</if>"
			+ "<if test=\"rev_datetime != null and rev_datetime != ''\">"
			+ ",rev_datetime = #{rev_datetime} "
			+ "</if>"
			+ "<if test=\"rev_name != null and rev_name != ''\">"
			+ ",rev_name = #{rev_name} "
			+ "</if>"
			+ "<if test=\"rev_phone != null and rev_phone != ''\">"
			+ ",rev_phone = #{rev_phone} "
			+ "</if>"
			+ "<if test=\"rev_state != null and rev_state != ''\">"
			+ ",rev_state = #{rev_state} "
			+ "</if>"
			+ "<if test=\"rev_naveruserid != null and rev_naveruserid != ''\">"
			+ ",rev_naveruserid = #{rev_naveruserid} "
			+ "</if>"
			+ "<if test=\"rev_bookingtype != null and rev_bookingtype != ''\">"
			+ ",rev_bookingtype = #{rev_bookingtype} "
			+ "</if>"
			+ "<if test=\"rev_platformtype != null and rev_platformtype != ''\">"
			+ ",rev_platformtype = #{rev_platformtype} "
			+ "</if>"
			+ "<if test=\"rev_cancelleddesc != null and rev_cancelleddesc != ''\">"
			+ ",rev_cancelleddesc = #{rev_cancelleddesc} "
			+ "</if>"
			+ "<if test=\"rev_email != null and rev_email != ''\">"
			+ ",rev_email = #{rev_email} "
			+ "</if>"
			+ "<if test=\"rev_userrequest != null and rev_userrequest != ''\">"
			+ ",rev_userrequest = #{rev_userrequest} "
			+ "</if>"
			+ "<if test=\"rev_prebookingkey != null and rev_prebookingkey != ''\">"
			+ ",rev_prebookingkey = #{rev_prebookingkey} "
			+ "</if>"
			+ "<if test=\"rev_visitorname != null and rev_visitorname != ''\">"
			+ ",rev_visitorname = #{rev_visitorname} "
			+ "</if>"
			+ "<if test=\"rev_visitorphone != null and rev_visitorphone != ''\">"
			+ ",rev_visitorphone = #{rev_visitorphone} "
			+ "</if>"
			+ "<if test=\"rev_resno != null and rev_resno != ''\">"
			+ ",rev_resno = #{rev_resno} "
			+ "</if>"
			+ "<if test=\"rev_customformdata != null and rev_customformdata != ''\">"
			+ ",rev_customformdata = #{rev_customformdata} "
			+ "</if>"
			+ "<if test=\"rev_itemoptions != null and rev_itemoptions != ''\">"
			+ ",rev_itemoptions = #{rev_itemoptions} "
			+ "</if>"
			+ "<if test=\"rev_ptno != null and rev_ptno != ''\">"
			+ ",rev_ptno = #{rev_ptno} "
			+ "</if>"
			+ "<if test=\"rev_date != null and rev_date != ''\">"
			+ ",rev_date = #{rev_date} "
			+ "</if>"
			+ "<if test=\"rev_time != null and rev_time != ''\">"
			+ ",rev_time = #{rev_time} "
			+ "</if>"
			+ "<if test=\"rev_confirm != null and rev_confirm != ''\">"
			+ ",rev_confirm = #{rev_confirm} "
			+ "</if>"
			+ "<if test=\"rev_reservationname != null and rev_reservationname != ''\">"
			+ ",rev_reservationname = #{rev_reservationname} "
			+ "</if>"
			+ "<if test=\"rev_period != null and rev_period != ''\">"
			+ ",rev_period = #{rev_period} "
			+ "</if>"
			+ "<if test=\"rev_cell != null and rev_cell != ''\">"
			+ ",rev_cell = #{rev_cell} "
			+ "</if>"
			+ "WHERE 0=0 "
			+ "AND rev_bookingkey = #{rev_bookingkey}"
			+ "</script>")
	public void updateOnlineReserve(CrmRevptNaverVO vo) throws Exception;
}
