package kr.ondoc.mapper.sybase.crm;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import kr.ondoc.domain.sybase.crm.CrmReserveCancelVO;
import kr.ondoc.domain.sybase.crm.CrmReserveGubunVO;
import kr.ondoc.domain.sybase.crm.CrmReserveParamVO;
import kr.ondoc.domain.sybase.crm.CrmReserveVO;
import kr.ondoc.domain.sybase.crm.CrmWorkplanParamVO;
import kr.ondoc.domain.sybase.crm.CrmWorkplanVO;


public interface CrmReserveMapper {
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT bmr_code, bmr_name, bmr_kwanm, bmr_hosname, bmr_docname, rev_seq, rev_ptno, rev_date, TRIM(rev_time) AS rev_time, rev_name, "
			+ "rev_memo, rev_examgu, rev_yage, rev_sex, rev_color, rev_tel_no, rev_hpno, rev_email, rev_gubun, "
			//rev_hcode값 수정시 rev_uphcode값만 업데이트하여 select시 rev_uphcode값이 우선이고 값이 없으면 rev_hcode값을 가져오도록 함
			+ "CASE WHEN rev_uphcode <> '' THEN rev_uphcode ELSE rev_hcode END AS rev_hcode "
			+ "FROM revpt AS RP "
			+ "INNER JOIN "
			+ "		(SELECT * FROM medroom"
			+ "			WHERE 0=0 AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y') AND bmr_use='Y') AS MD "
			+ "ON RP.rev_medroom=MD.bmr_code  "
			+ "]]>"
			+ "<if test=\"month != null and month != ''\">"
			+ "<![CDATA["
			+ "AND RP.rev_date like '${month}__' "
			+ "]]>"
			+ "</if>"
			+ "<if test=\"dates != null and dates != ''\">"
			+ "AND RP.rev_date in (${dates}) "
			+ "</if>"
			+ "<if test=\"date != null and date != ''\">"
			+ "AND RP.rev_date = #{date} "
			+ "</if>"
			+ "<if test=\"code != null and code != ''\">"
			+ "AND MD.bmr_code = #{code} "
			+ "</if>"
			+ "<if test=\"room_name != null and room_name != ''\">"
			+ "AND MD.bmr_name = #{room_name} "
			+ "</if>"
			+ "<if test=\"time != null and time != '' and time == '09'\">"
			+ " AND LEFT(RP.rev_time, 2) in ('00', '01', '02', '03', '04', '05', '06', '07', '08', '09') "
			+ "</if>"
			+ "<if test=\"time != null and time != '' and time == '18'\">"
			+ " AND LEFT(RP.rev_time, 2) in ('18', '19', '20', '21', '22', '23') "
			+ "</if>"
			+ "<if test=\"time != null and time != '' and time != '09' and time != '18'\">"
			+ " AND LEFT(RP.rev_time, 2) in (${time}) "
			+ "</if>"
			+ "AND (RP.rev_canid is null OR RP.rev_canid = '') "
			+ "ORDER BY RP.rev_time ASC "
			+ "</script>")
	public List<CrmReserveVO> selectReserve(CrmReserveParamVO vo) throws Exception;
	
	@Update("<script>"
			+ "UPDATE revpt SET "
			+ "rev_seq = rev_seq "
			+ "<if test=\"date != null and date != ''\">"
			+ ",rev_date = #{date} "
			+ "</if>"
			+ "<if test=\"time != null and time != ''\">"
			+ ",rev_time = #{time} "
			+ "</if>"
			+ "<if test=\"medroom != null and medroom != ''\">"
			+ ",rev_medroom = #{medroom} "
			+ "</if>"
			+ "<if test=\"kwa != null and kwa != ''\">"
			+ ",rev_kwa = #{kwa} "
			+ "</if>"
			+ "<if test=\"name != null and name != ''\">"
			+ ",rev_name = #{name} "
			+ "</if>"
			+ "<if test=\"resno != null and resno != ''\">"
			+ ",rev_resno = #{resno} "
			+ "</if>"
			+ "<if test=\"tel != null and tel != ''\">"
			+ ",rev_tel_no = #{tel} "
			+ "</if>"
			+ "<if test=\"hpno != null and hpno != ''\">"
			+ ",rev_hpno = #{hpno} "
			+ "</if>"
			+ "<if test=\"memo != null and memo != ''\">"
			+ ",rev_memo = #{memo} "
			+ "</if>"
			+ "<if test=\"revchk != null and revchk != ''\">"
			+ ",rev_revchk = #{revchk} "
			+ "</if>"
			+ "<if test=\"email != null and email != ''\">"
			+ ",rev_email = #{email} "
			+ "</if>"
			+ "<if test=\"gubun != null and gubun != ''\">"
			+ ",rev_gubun = #{gubun} "
			+ "</if>"
			+ "<if test=\"yage != null and yage != ''\">"
			+ ",rev_yage = #{yage} "
			+ "</if>"
			+ "<if test=\"sex != null and sex != ''\">"
			+ ",rev_sex = #{sex} "
			+ "</if>"
			+ "<if test=\"color != null and color != ''\">"
			+ ",rev_color = #{color} "
			+ "</if>"
			+ "<if test=\"sendchk != null and sendchk != ''\">"
			+ ",rev_sendchk = #{sendchk} "
			+ "</if>"
			+ "<if test=\"hcode != null and hcode != ''\">"
			+ ",rev_hcode = #{hcode} "
			+ "</if>"
			
			+ "<if test=\"uphcode != null and uphcode != ''\">"
			+ ",rev_uphcode = #{uphcode} "
			+ "</if>"
			+ "<if test=\"upsendchk != null and upsendchk != ''\">"
			+ ",rev_upsendchk = #{upsendchk} "
			+ "</if>"
			+ "<if test=\"upid != null and upid != ''\">"
			+ ",rev_upid = #{upid} "
			+ "</if>"
			+ "<if test=\"upid != null and upid != ''\">"
			+ ",rev_uptime = GETDATE() "
			+ "</if>"
			+ "<if test=\"reccode != null and reccode != ''\">"
			+ ",rev_reccode = #{reccode} "
			+ "</if>"
			+ "<if test=\"canmemo != null and canmemo != ''\">"
			+ ",rev_canmemo = #{canmemo} "
			+ "</if>"
			+ "<if test=\"cansendchk != null and cansendchk != ''\">"
			+ ",rev_cansendchk = #{cansendchk} "
			+ "</if>"
			+ "<if test=\"canid != null and canid != ''\">"
			+ ",rev_canid = #{canid} "
			+ "</if>"
			+ "<if test=\"canid != null and canid != ''\">"
			+ ",rev_cantime = GETDATE() "
			+ "</if>"
			+ "WHERE 0=0 "
			+ "AND rev_seq = #{seq}"
			+ "</script>")
	public void updateReserve(CrmReserveParamVO vo) throws Exception;
	
	@Insert("<script>"
			+ "INSERT INTO revpt ("
			+ "rev_date, rev_ptno, rev_time, rev_medroom, rev_kwa, "
			+ "rev_name, rev_resno, rev_tel_no, rev_hpno, rev_memo,"
			+ "rev_revchk, rev_mngrno, rev_id, rev_email, rev_gubun, "
			+ "rev_yage, rev_sex, rev_color, rev_sendchk, rev_hcode, con_seq) "
			+ "VALUES ( "
			+ "#{date}, #{ptno}, #{time}, #{medroom}, #{kwa}, "
			+ "#{name}, #{resno}, #{tel}, #{hpno}, #{memo},"
			+ "'0', '1', #{id}, #{email}, #{gubun},"
			+ "#{yage}, #{sex}, #{color}, #{sendchk}, #{hcode}, #{con_seq})"
			+ "</script>")
	public void insertReserve(CrmReserveParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "SELECT * FROM rsv_hgubun ORDER BY rsv_hcode"
			+ "</script>")
	public List<CrmReserveGubunVO> selectGubun() throws Exception;
	
	@Select("<script>"
			+ "SELECT * FROM rsv_cancel ORDER BY rsc_code"
			+ "</script>")
	public List<CrmReserveCancelVO> selectCancel() throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT #{reserveDate} AS reserveDate, bdw_time AS usableTime, (bdw_cnt-bdw_re_cnt) AS reserveUsableCount, mrv_re_cnt AS mobileCount, '${code}' AS code "
			+ "FROM (SELECT bdw_date, bdw_time, bdw_cnt, COUNT(rev_time) AS bdw_re_cnt, COUNT(mrv_time) AS mrv_re_cnt "
			+ "			FROM (SELECT WP.bdw_code, WP.bdw_date, WP.bdw_time, WP.bdw_cnt, RV.rev_time, MRV.mrv_time "
			+ "				FROM (SELECT bdw_code, bdw_date, bdw_time, bdw_cnt "
			+ "						FROM doc_workplan "
			+ "						WHERE 0=0 "
			+ " 					AND bdw_code=#{code} "
			+ "						AND bdw_daygu=(SELECT DATEPART(WEEKDAY, #{reserveDate})-1) "
			+ "						AND bdw_hosnum=(SELECT bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y')"
			+ "						AND bdw_date = (SELECT MAX(bdw_date) FROM doc_workplan WHERE ((bdw_daygu=(SELECT DATEPART(WEEKDAY, #{reserveDate})-1) AND bdw_gubun='0' AND bdw_date<=#{reserveDate}) OR (bdw_date = #{reserveDate} AND bdw_gubun = '1')) AND bdw_code=#{code} AND bdw_hosnum=(SELECT bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y')) "
			+ "						AND bdw_gubun = (SELECT MAX(bdw_gubun) FROM doc_workplan WHERE ((bdw_daygu=(SELECT DATEPART(WEEKDAY, #{reserveDate})-1) AND bdw_gubun='0' AND bdw_date<=#{reserveDate}) OR (bdw_date = #{reserveDate} AND bdw_gubun = '1')) AND bdw_code=#{code} AND bdw_hosnum=(SELECT bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y')) "
			+ "						) AS WP "
			+ "						LEFT OUTER JOIN revpt AS RV "
			+ "						ON RV.rev_date=#{reserveDate} AND RV.rev_medroom=#{code} AND WP.bdw_time=RV.rev_time AND RV.rev_canid is null"
			+ "						LEFT OUTER JOIN (SELECT * FROM mob_revpt WHERE mrv_status=0) AS MRV "
			+ "						ON MRV.mrv_date=#{reserveDate} AND wp.bdw_time=MRV.mrv_time ) AS TB "
			+ "						GROUP BY bdw_date, bdw_time, bdw_cnt) AS TB "
			+ "ORDER BY usableTime   "
			+ "]]>"
			+ "</script>")
	public List<CrmWorkplanVO> selectWorkPlan(CrmWorkplanParamVO vo) throws Exception;
	
	@Select("<script>"
			+ "<![CDATA["
			+ "SELECT bmr_code, bmr_name, bmr_kwanm, bmr_hosname, bmr_docname, rev_seq, rev_ptno, rev_date, TRIM(rev_time) AS rev_time, rev_name, con_seq,"
			+ "rev_memo, rev_examgu, rev_yage, rev_sex, rev_color, rev_tel_no, rev_hpno, rev_email, rev_gubun, "
			//rev_hcode값 수정시 rev_uphcode값만 업데이트하여 select시 rev_uphcode값이 우선이고 값이 없으면 rev_hcode값을 가져오도록 함
			+ "CASE WHEN rev_uphcode <> '' THEN rev_uphcode ELSE rev_hcode END AS rev_hcode "
			+ "FROM revpt AS RP "
			+ "INNER JOIN "
			+ "		(SELECT * FROM medroom"
			+ "			WHERE 0=0 AND bmr_hosnum = (SELECT bhi_hosnum FROM hosinfo WHERE bhi_usechk='Y') AND bmr_use='Y') AS MD "
			+ "ON RP.rev_medroom=MD.bmr_code  "
			+ "]]>"
			+ "<if test=\"seqs != null and seqs != ''\">"
			+ "AND RP.con_seq in (${seqs}) "
			+ "</if>"
			+ "AND (RP.rev_canid is null OR RP.rev_canid = '') "
			+ "ORDER BY RP.rev_time ASC "
			+ "</script>")
	public List<CrmReserveVO> selectCounselRelationReserve(String seqs) throws Exception;
}
